import { tpl } from "./model";

export function detectMake(make: string) {
  const currentMake: tpl = {
    Hyundai: "Hyundai",
    Genesis: "Genesis",
    Kia: "Kia",
    ChevroletGMDaewoo: "Chevrolet (GM Daewoo)",
    ["Renault-KoreaSamsung"]: "Renault Korea (Samsung)",
    KG_Mobility_Ssangyong: "KG Mobility (Ssangyong)",
    Others: "Others",
    Audi: "Audi",
    BMW: "BMW",
    ["Mercedes-Benz"]: "Mercedes-Benz",
    Porsche: "Porsche",
    Volvo: "Volvo",
    ["Land Rover"]: "Land Rover",
    Lincoln: "Lincoln",
    Tesla: "Tesla",
    Jeep: "Jeep",
    Maserati: "Maserati",
    Jaguar: "Jaguar",
    Infiniti: "Infiniti",
    Toyota: "Toyota",
    Bentley: "Bentley",
    Ford: "Ford",
    Peugeot: "Peugeot",
    Lexus: "Lexus",
    Cadillac: "Cadillac",
    Chrysler: "Chrysler",
    Mini: "Mini",
    Honda: "Honda",
    Volkswagen: "Volkswagen",
    Nissan: "Nissan",
    Astonmartin: "Astonmartin",
    Ferrari: "Ferrari",
    ["Rolls-Royce"]: "Rolls-Royce",
    ["Citroen-DS"]: "Citroen-DS",
    Hummer: "Hummer",
    Lamborghini: "Lamborghini",
    Polestar: "Polestar",
    Mclaren: "Mclaren",
    Dodge: "Dodge",
    Fiat: "Fiat",
    Lotus: "Lotus",
    Saab: "Saab",
    GMC: "GMC",
    DFSK: "DFSK",
    Daihatsu: "Daihatsu",
    Smart: "Smart",
    Suzuki: "Suzuki",
    Mitsuoka: "Mitsuoka",
    ["Baic Yinxiang"]: "Baic Yinxiang",
    Mazda: "Mazda",
    Maybach: "Maybach",
    Subaru: "Subaru",
    Acura: "Acura",
    Mitsubishi: "Mitsubishi",
    Opel: "Opel",
    ["Alfa Romeo"]: "Alfa Romeo",
    Renault: "Renault",
    Mercury: "Mercury",
  };
  return currentMake[make];
}
