export const mainComponent: string[] = [
  "Self-diagnosis",
  "Prime Mover",
  "Gearbox",
  "Power Transmission",
  "Steering",
  "Braking",
  "Electricity",
  "Fuel",
  "High power electric device",
];
export const componentList: string[] = [
  "Prime Mover",
  "Gearbox",
  "Operating state (idling)",
  "Oil Leakage Oil",
  "Oil flow rate",
  "Coolant leakage",
  "Automatic Transmission (A / T)",
  "Clutch Assembly",
  "Constant Speed Joint",
  "Chuchin shaft and Bearing",
  "Differential Gear",
  "Power steering operation Oil leakage",
  "Operating Status",
  "Brake Master Cylinder Oil Leakage",
  "Brake oil leakage",
  "Power supply status",
  "Generator output",
  "Starting Motor",
  "Wiper Motor Function",
  "Indoor ventilating motor",
  "Radiator Fan Motor",
  "Window Motor",
  "Fuel leakage (LP gas included)",
  "Manual transmission (M / T)",
  "Common Rail",
  "Charging port insulation state",
  "Drive battery isolation state",
  "High power electrical wiring status(connection terminal, cloth, protection mechanism)",
];
